### ISSUE TITLE
Translated string is not appearing on the withdraw request list on the admin panel.

### ISSUE THREAD

**Issue by J-H-Mojumder** [getdokan/dokan#2191] opened 2024-03-05 10:57 UTC
### Bug Description

If a string of the Bank form of Dokan is changed using the translation method as shown in [this screenshot](https://snipboard.io/6id4uL.jpg), the change is applied on the frontend as shown [here](https://snipboard.io/LJI9cp.jpg), but the change is not reflected on the withdraw request list on the admin pane as shown in [this screenshot](https://snipboard.io/8oibVQ.jpg).

### Step To Reproduce

1. Please change the IBAN-related strings using the translation method.
2. You will find the string translated on the vendor dashboard's `Settings > Payments` page.
3. Send a withdraw request from the vendor dashboard and the request caught by the admin will not reflect the changed string.

### Expected Behaviour

The change should appear everywhere on the site.

### Actual Behaviour

The change does not appear on the admin panel's withdraw request list.

**Comment by shohag121** [comment] 2024-03-25 06:43
@J-H-Mojumder Bhai, 

The issue is not reproducible.
Have you tried clearing the cache?

Did the user choose the correct language from the profile settings?



![Image](https://github.com/getdokan/dokan/assets/5476784/f9fb5de2-9514-457e-8c53-06488542a411)
![Image](https://github.com/getdokan/dokan/assets/5476784/c2f5e1cb-0347-4609-9c6c-6757a5e17270)

Please let me know.

**Comment by shohag121** [comment] 2024-04-04 08:30
Closing this issue as per @shams-sadek1981 Bhai's instruction.

**Closed by shohag121** 2024-04-04 08:30 UTC
Labels: Type: Bug
