### ISSUE TITLE
⚠️⚠️⚠️ STRIPE ONBOARDING / DOKAN SELLERS ONBOARDING: Bugs and Wrong Redirections

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2228] opened 2024-04-05 21:55 UTC
### Bug Description

Following up on customer support ticket #55595

I noticed 3 bugs with Stripe Express Onboarding and Dokan Vendor Onboarding:

- [ ] 1. Even if we complete the whole Stripe Onboarding, we still see in Dokan that we have not, and then we need to Finish the Stripe Onboarding again for it to work

- [ ] 2. On the first time, sellers finish the Stripe Onboarding, they are always redirected to their Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup.

- [ ] 3. If sellers did the Stripe process in another language than the default website language like French, they are redirected to the English Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup in the right language.

Here videos as proof that it never works properly:
- French example from 7min05 to 11min20: ask video in customer support ticket #55595

- English example from 9min50 to 14:15min : ask video in customer support ticket #55595

- Other english example from 9min40 to 13min40: ask video in customer support ticket #55595

- Other english example from 10min to 15min: ask video in customer support ticket #55595

So it is a constant bug that happens and that I reported various times with always the same answer from customer support that you do not have the bug when you do the test but I constantly have it and I already did the test in the past with default theme and no plugin with same results.

Could you please check it out again and let me know how to fix it because I have this bug constantly for any registration in any language I have tried.

Waiting for your news

### Step To Reproduce

 Stripe Express Onboarding and Dokan Vendor Onboarding:

### Expected Behaviour

1. Even if we complete the whole Stripe Onboarding, we still see in Dokan that we have not, and then we need to Finish the Stripe Onboarding again for it to work

2. On the first time sellers finish the Stripe Onboarding, they are always redirected to their Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup.

3. And if sellers did the Stripe process in another language than the default website language like French, they are redirected to the English Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup in the right language.

### Actual Behaviour

1. Even if we complete the whole Stripe Onboarding, we still see in Dokan that we have not, and then we need to Finish the Stripe Onboarding again for it to work

2. On the first time sellers finish the Stripe Onboarding, they are always redirected to their Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup.

3. And if sellers did the Stripe process in another language than the default website language like French, they are redirected to the English Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup in the right language.

### Environment (please complete the following information)

```shell
1. Dokan Version: [all]
2. Dokan Pro Version: [all]
3. WooCommerce Version: [all]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by mralaminahamed** [comment] 2024-04-17 10:47
hello @Sophie-2e, thank you for your report and for allowing us to investigate the potential language redirection issue during the Stripe onboarding process. 

After a thorough investigation and testing, we were unable to reproduce the reported behavior. Based on our findings, the language redirection appears to be functioning correctly, and sellers are being redirected to the localized version of the Dokan Onboarding > Payment Setup page according to their selected language preferences.

Since we could not replicate the issue and you have confirmed that it is no longer a concern, we will be closing this issue. However, we will continue to monitor the Stripe onboarding flow and address any future reports of localization problems promptly.

We appreciate you taking the time to report this potential issue and for your understanding throughout our investigation process. Your feedback helps us improve the Dokan platform and ensure a seamless experience for all users.

If you encounter any other issues or have any further concerns, please feel free to open a new issue or contact our support team.

**Closed by mralaminahamed** 2024-04-17 10:47 UTC
Labels: focus: payments

**Comment by mralaminahamed** [comment] 2024-05-29 13:10
@Sophie-2e , good day to you! I hope this message finds you well. I would like to inform you that **we have addressed the issue regarding the wrong redirection during the Stripe Express onboarding process when a vendor uses a language other than the default language.**

This fix will be **included in an upcoming release** of Dokan Pro. Please stay tuned for the latest update. Have a wonderful day ahead!

**Comment by Sophie-2e** [comment] 2024-05-30 13:34
Happy Friday @mralaminahamed , you just made my day with such good news 😉 Looking forward to the next Dokan Pro update then, is it for Dokan Pro 3.11.2 ? or later?

**Comment by mralaminahamed** [comment] 2024-05-30 14:23
@Sophie-2e, I'm so glad to hear that the news about addressing the Stripe Express onboarding issue has brought you joy. It's our pleasure to provide solutions that enhance the user experience for our valued community members like yourself.

Thank you for your follow-up question regarding the release version. You're absolutely right; the fix will be included in Dokan Pro 3.11.2 or a later version, depending on our development and testing timeline. Our team is working diligently to ensure the update meets our high standards for quality and reliability.

Rest assured, as soon as the update is available, we will promptly notify you and the rest of our user community. In the meantime, please feel free to reach out if you have any other questions or concerns. We're always here to support you.

Wishing you a wonderful weekend filled with joy and relaxation! 🙌

**Comment by Sophie-2e** [comment] 2024-05-30 16:09
@mralaminahamed ok hopefully will be released next month🤞That will be really awesome! 

Then I look forward to the new updates next month as it seems that a lot of major issues are currently being addressed. And Gausul and Sazzat will keep me posted on the release of this fix 😉

Just want to say big kudos to you, @mralaminahamed because I see all the hard work you've put in over the last few months, and you are doing amazing, keep rocking 👌💪💯

**Comment by mralaminahamed** [comment] 2024-05-30 16:13
@Sophie-2e, thank you for your kind words and encouragement – your support means a lot
