### ISSUE TITLE
SELLER PACKS SUBSCRIPTION - Dokan Subscription Cancelled email template  - sent to admin -> should be sent on the day the user clicks on cancel

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2044] opened 2023-10-09 16:47 UTC
### Bug Description

When vendors cancel their subscriptions, before upgrading/downgrading, the admin does not receive the Dokan Subscription Cancelled email template anymore.

### Step To Reproduce

Go on a vendor dashboard > subscription > cancel your current subscription 
Check admin email > no email received

### Expected Behaviour

When vendors cancel their subscriptions, before upgrading/downgrading, the admin should receive the Dokan Subscription Cancelled email template.

### Actual Behaviour

When vendors cancel their subscriptions, before upgrading/downgrading, the admin does not receive the Dokan Subscription Cancelled email template anymore.

### Additional Information

Use Stripe Express

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9]
2. Dokan Pro Version: [3.9]
3. WooCommerce Version: [8.1.1]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by nurul-umbhiya** [comment] 2023-10-10 07:54
@Sophie-2e Couldn't reproduce this issue on our end. Kindly create a support ticket for this. They'll take care of it.

**Comment by Sophie-2e** [comment] 2023-10-10 09:13
@nurul-umbhiya I already opened a customer support ticket: https://app.dokan.co/support/22323 and Yeasin did reproduce this error on his end too...according to him "We have already created an issue report on our side and anticipate that it will be resolved as soon as possible." which is why I opened the GitHub report, so I can be sure that it is really taking care of.

Waiting for your news.

**Comment by Sophie-2e** [comment] 2023-10-31 19:26
Hello @nurul-umbhiya, So I understand how you can reproduce the error, instead of the admin receiving the notification on the day that the vendor has cancelled his subscription, the admin only knows it on the next billing cycle which is in my case every month, so I received the cancellation email today, while the vendor cancelled the subscription 3 weeks ago. Not practical for the admin who cannot make accurate prevision if he/she only knows on the next billing cycle day, nor try to contact the vendor to keep them on the platform. 

Also weird that all subscriptions got cancelled today even though the vendor did subscribe to another pack so he has to resubscribe again which does not make sense as he already subscribed to a new pack 3 weeks ago which lasts for 1 year with a recurring payment every month. What is the expected behaviour when a vendor cancels a subscription and upgrades/downgrades right after?

Waiting for your news,
Thanks

**Comment by Sophie-2e** [comment] 2023-12-30 17:09
@nurul-umbhiya @imtiaz-pranto any update on this?

**Comment by Sophie-2e** [comment] 2024-02-11 18:50
@nurul-umbhiya @imtiaz-pranto reported since october, still not fix with latest updates and, since latest updates cannot subscribe to any recurrent packs with Stripe Express, still not able to renew, so still stuck on this. Stripe Express module need to be fix urgently. What is the timeline?

**Comment by Sophie-2e** [comment] 2024-03-07 13:02
Hello @nurul-umbhiya , @imtiaz-pranto , now the subscription/renewal issue because of the compatibility issue with WPML is resolved, I could test this again. So the email is sent indeed, but instead of the admin receiving the notification on the day that the vendor has cancelled his subscription, the admin only knows it on the next billing cycle which is in my case every month, so I received the cancellation email today, while the vendor cancelled the subscription 3 weeks ago. Not practical for the admin who cannot make accurate prevision if he/she only knows on the next billing cycle day, nor try to contact the vendor to keep them on the platform. I will go ahead and change the title of this GitHub feature improvement request. 

(This is NOT an emergency, there are other priorities 😉)

**Comment by MdAsifHossainNadim** [comment] 2024-04-17 06:45
@Sophie-2e Currently, we have been unable to reproduce the issue you reported to us. We kindly request that you watch the [video](https://streamable.com/x0pjck) resources provided for further clarification and re-examine the situation If the problem persists, please create a new support ticket and collaborate with our support team for detailed assistance.

If the issue is no longer reproducible on your end, please inform us accordingly so that we can proceed to close the issue.

Thank you for your cooperation and understanding.

**Comment by MdAsifHossainNadim** [comment] 2024-04-23 05:06
@mr-gausulazam Vhai, please check [this video](https://streamable.com/x0pjck). As we discussed this issue is not raising from the plugin end. Is this problem site-specific...???

Awaiting your reply...

**Comment by Sophie-2e** [comment] 2024-04-23 09:02
Hey @MdAsifHossainNadim , I just redid a full test with Dokan 3.10.3. Note that I also use WPML. Whatever the language I don't receive the cancel email and I have some issues when sellers orders/cancel the subscription in another language than the default language. Please @mr-gausulazam send the video to @MdAsifHossainNadim so I can see all the tests with Dokan 3.10.3 and tell me how to fix it.

**Comment by MdAsifHossainNadim** [comment] 2024-04-25 07:26
@mr-gausulazam @Sophie-2e Related with [update: email refactor](https://github.com/getdokan/dokan-pro/pull/2655) PR.

**Comment by Sophie-2e** [comment] 2024-04-25 11:13
@MdAsifHossainNadim cannot access the private repository, did you get the full test video I sent on the 23rd of April to @mr-gausulazam made with Dokan 3.10.3?  

To go faster, here is conversation with Gausul:

Gausul: We have detected an issue on your website and plugin level. The problem occurs when creating a free subscription plan with a price of 0. If you set any price for the subscription plan, the issue does not occur, and the email triggers properly. However, this issue only happens for the free subscription plan. Our team is actively working to resolve this issue. Once they resolve it, I will let you know.

Me: Would make sense that it is actually the default behaviour to don't receive the cancel email on the 0 euro subscription because it is not a recurrent subscription, which is the only one that is NOT recurrent. So indeed it is probably the default behaviour.
But **all the other paid subscription are recurrent** and **they are the ones that are suposed to receive the email right after the seller click on cancel** but do not when sellers click on cancel button.

So I don't think it has anything to do with the 0 euro.

Please check again video and replicate exact test (seller dashboard language + packs) so you successfully reproduce errors yourself and start working on a resolution.

**Comment by mr-gausulazam** [comment] 2024-05-14 05:01
@MdAsifHossainNadim bhai, the email only sent to the English language. There is a need to multilingual support.

**Comment by Sophie-2e** [comment] 2024-05-14 06:15
@MdAsifHossainNadim and note that translation used to work fine before Dokan 3.9

**Comment by MdAsifHossainNadim** [comment] 2024-06-10 03:24
@Sophie-2e Could you please confirm, whether you are not receiving any email notifications when you cancel your subscription after setting a date for the pack validity from your product. If this is correct, kindly review the provided [screencast](https://streamable.com/ug8d60) and let me know your findings…

If my understanding is incorrect, could you please provide a brief screencast demonstrating what you expect to happen...?

**CC:** @mr-gausulazam

**Comment by Sophie-2e** [comment] 2024-06-10 08:48
@MdAsifHossainNadim as explained last time (https://github.com/getdokan/dokan/issues/2044#issuecomment-2106346897), you only get the issue with the recurring pack but you keep testing with a non-recurring pack. So when you do a test with a **RECURRING PACK** (**which means that renews every week, month whatever, and that renews automatically for a certain period (one month, a year etc...), then you will have the error** and so you will receive no email. Please @mr-gausulazam , I don't know how to explain that the issue happens with **RECURRING** subscription 😅 Thanks for your help 🙌

**Comment by mr-gausulazam** [comment] 2024-06-11 08:40
@Sophie-2e I have explained this to the @MdAsifHossainNadim bhai properly. I hope he will resolve it from our end.

**Comment by MdAsifHossainNadim** [comment] 2024-06-12 05:24
@Sophie-2e Kindly check this [screencast](https://streamable.com/v3ok7r) for recurring product cancellation email & follow up [Subscription cancellation email](https://github.com/getdokan/dokan-pro/pull/3432) PR for getting update.

**Comment by Sophie-2e** [comment] 2024-06-12 06:38
Hello @MdAsifHossainNadim, thanks for the video, for the email that was sent in your video, I guess it is the one sent to the vendor that we see in your video but still not the one that is sent to the admin. 2 emails are supposed to be sent when vendor cancels subcription, one to seller, and one to admin. So not sure which one you do not receive but you also miss one in your test:
- the one sent to admin manageable via Woocommerce > Settings > emails: dokan-pro/modules/subscription/templates/emails/html/dokan-subscription-cancelled.php

- the one sent to sellers manageable via Dokan > Settings > Vendor subscription: 
Concerning the page your provided that I can follow up is a 404 page, please resend the correct link.
![Screenshot 2024-06-12 at 08 37 20](https://github.com/getdokan/dokan/assets/131655229/b4c9c865-e55d-4eb7-97ab-a1cc554fb33f)

Here again, I tested when I cancel, I do not receive any email (nothing sent to the seller and nothing sent to the admin) but I don't use daily payment like you do, it is a monthly payment and recurring for a year, not sure if it could be the reason impacting the email not being sent: https://www.loom.com/share/d850cb8147f94a1da7b238529b574d80?sid=dfbcda38-d74f-45d2-9286-6caecf78bc81

The Dokan Support team (and @mr-gausulazam) has access to the staging website if you need to check it out there.

Will be waiting for your reply

**Comment by Mohaiminulislam1989** [comment] 2024-06-24 08:46
@MdAsifHossainNadim, @mr-gausulazam, Please check from your side.

**Closed** 2024-07-08 06:05 UTC
Labels: focus: subscription, focus: email

**Comment by Sophie-2e** [comment] 2024-07-24 12:43
Thank you so much for fixing this issue @MdAsifHossainNadim and @Mohaiminulislam1989 , just tested it with Dokan 3.10.4+ Pro 3.10.3, and it works like a charm now 💯 You rock guys ! 🎉
