### ISSUE TITLE
Big issue with Stripe Express Refund

### ISSUE THREAD

**Issue by daniel-toader** [getdokan/dokan#2201] opened 2024-03-13 05:29 UTC
### Bug Description

When a vendor requests a refund for an order paid with Stripe Express, the following occurs:

1.The admin receives the email with the refund request.

2.The refund appears immediately canceled in the Dokan dashboard without the admin taking any action.

3.In the Stripe dashboard, the refund is processed, and the amount is taken from the admin connect account balance.

This is rather concerning and requires investigation by the team.

Additionally, this function needs some form of protection.

Thank you!

I will also investigate further the next time a refund will be needed.

-This issue does't happen when the payment is COD. The refund request appears as pending in the Dokan dashboard.

-There are no errors reported by the developer tools inside Stripe.

**Comment by shohag121** [comment] 2024-03-14 05:43
@StalinDurjo @shashwatahalder01 Bhai,

Would you please check that the issue is reproducible at the plugin level?

**Comment by StalinDurjo** [comment] 2024-03-14 09:31
@shohag121 bhai, this issue is reproducible.

**Comment by daniel-toader** [comment] 2024-03-15 19:00
Yep!

Today I refunded another order, the outcome was the same.

I enabled the WooCommerce log this time:

Refund processing for the order #XXXXX failed.

**Comment by mralaminahamed** [comment] 2024-03-20 10:02
Thank you for bringing this issue to our attention and providing a detailed description of the problem you encountered with **Stripe Express** refunds. We appreciate your thorough investigation and the additional insights you've shared regarding refunds processed through other payment methods like COD.

Our team will investigate this issue further to identify the root cause and implement necessary fixes. Rest assured that we'll prioritize addressing this concern, and the fix will be included in a future release of **Dokan Pro**.

**Closed** 2024-03-27 10:26 UTC
Labels: Has Pull Request, Dokan Pro, :moneybag: StripeExpress
