### ISSUE TITLE
Bug on using Dokan Store Contact Form

### ISSUE THREAD

**Issue by awilness** [getdokan/dokan#2016] opened 2023-09-26 10:38 UTC
### Bug Description

widget dokan-store-widget dokan-store-contact doesn’t work if the email is yahoo.com (example: [testlegit@yahoo.com](mailto:testlegit@yahoo.com)) but when using other email like domain or google. it works well, the vendor can receive the test email

### Step To Reproduce

1. Go to 'vendors page'
2. Fill Up 'Contact form widget'
3. On your email, put a yahoo mail  'testemail@yahoo.com'
4. Put your description or short message
5. click 'Send Message;
6. You will see the 'Email sent successfully!' message.
7. Check the vendors email, there's no email from Yahoo

### Expected Behaviour

Expected to receive any email from any domain

### Actual Behaviour

so far, we found out that we can't receive any inquiry if the customer uses a yahoo.com email 

### Environment (please complete the following information)

```shell
1. Dokan Version: Version 3.8.1
2. Dokan Pro Version: [e.g. v3.1.2]
3. WooCommerce Version: Version 7.8.2
4. Browser Chrome, Brave, Firefox
5. Current Theme: Astra Child
```

**Comment by Aunshon** [comment] 2023-11-10 04:52
Dear Client,

I hope this message finds you well. I wanted to address the issue you reported regarding the "dokan-store-contact" widget not working with Yahoo email addresses while functioning correctly with other domains such as Google.

After thorough investigation, it appears that the issue is related to Yahoo's email handling and not a problem with Dokan. Unfortunately, this is beyond our control.

As a result, I'm closing the GitHub issue for now. However, please don't hesitate to reach out if you encounter any further issues or if there's anything else we can assist you with. We're here to help.

Thank you for your understanding and cooperation.

**Closed by Aunshon** 2023-11-10 04:52 UTC
Labels: Type: Bug
