### ISSUE TITLE
⚠️⚠️ Refund Functions with Stripe Express - Impossible to process full refunds from Refund Request

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2232] opened 2024-04-12 12:27 UTC
### Bug Description

Following up on GITHIB #2110: https://github.com/getdokan/dokan/issues/2110 which has been closed while some issues are still there.

- [x] From refund request: Problem to fully refund an order because of tax errors

- [ ] From refund request: Problem to fully refund an order because no way of adding shipping cost

- [ ] From Coupon Store Credit request: Still cannot add the shipping cost to the refunded cost

- [x] Also noticed that in the refund request page, it is the user name of the customer that is displayed when it should be first name and last name like it is in the other detail

### Step To Reproduce

testing refund function from customer dashboard

### Expected Behaviour

That we can add the shipping costs + that we don't face the issue with tax errors

### Actual Behaviour

- [x] From refund request: Problem to fully refund an order because of tax errors:

<img width="450" alt="Screenshot 2024-04-12 at 14 24 55" src="https://github.com/getdokan/dokan/assets/131655229/b5a3ff4e-d5a2-4f81-aa42-1e1dbb252c38">

<img width="1051" alt="Screenshot 2024-04-12 at 14 24 29" src="https://github.com/getdokan/dokan/assets/131655229/1fd14f0b-1c99-4af8-a93a-a5280134e7b2">

- [ ] From refund request: Problem to fully refund an order because no way of adding shipping cost: 

<img width="450" alt="Screenshot 2024-04-12 at 14 24 55" src="https://github.com/getdokan/dokan/assets/131655229/b5a3ff4e-d5a2-4f81-aa42-1e1dbb252c38">

- [ ] From Coupon Store Credit request: Still cannot add the shipping cost to the refunded cost:

<img width="440" alt="Screenshot 2024-04-12 at 14 26 01" src="https://github.com/getdokan/dokan/assets/131655229/1b795f2f-66b5-4f4a-b85b-f13eb1a233c4">

- [x] Also noticed that in the refund request page, it is the user name of the customer that is displayed when it should be first name and last name like it is in the other detail

<img width="613" alt="Screenshot 2024-04-12 at 14 40 58" src="https://github.com/getdokan/dokan/assets/131655229/f445f423-dc56-4fe8-94ba-4e0e34f07149">

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.10.2]
2. Dokan Pro Version: [3.10.2]
3. WooCommerce Version: [8.7.0]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by mralaminahamed** [comment] 2024-04-25 04:45
@Sophie-2e, I have thoroughly tested the refund functionality from the customer dashboard using the provided steps, but I was unable to reproduce the reported issues. Both the vendor refund and RMA refund processes worked as expected without any tax errors or issues related to adding shipping costs.

To investigate, I followed these steps:

1. Placed a new order on the test site as a customer.
2. Initiated a refund request for that order from the customer dashboard.
3. Tested the refund process using the vendor refund option as well as the RMA refund option.
4. During both refund processes, I was able to include the shipping cost without any issues.
5. The tax calculations were also accurate, and no errors were encountered.
6. On the refund request page, the customer's first name and last name were displayed correctly.

I've recorded a video demonstrating the entire testing process, which you can find attached below. As you'll see, I couldn't reproduce any of the reported issues on my end.

[Video Attachment](https://drive.google.com/open?id=1-X63HWUJdA6esQ_3J1Z5cvKucOz3a6b1&usp=drive_fs)

However, I understand that the issue may be specific to a particular site or configuration.

Please let me know if you need any additional information or if you can provide access to a staging site exhibiting the reported problems.

**Comment by Sophie-2e** [comment] 2024-04-25 10:42
Hello @mralaminahamed, @mrabbani ,

No you did not test the right functions explained in this github because:
1. **you did not use Stripe Express** to pay the order, you used Cash on delivery. The title of the github expressly indicates that the issue occurs with Stripe Express. 
2. **You did not do a FULL refund but a Partial Refund** while the title of the github expressly indicates that the issue occurs with FULL refund
3. **You did not have any option to add the shipping cost so you definitely did not proceed with the refund of the delivery cost**, now you have tested and successfully reproduced the bug, you can proceed with working on fix.
4. You did not test the refund from the Vendor Order Detail in your video as you said in your last answer, but anyways, just read again the github issue with the 4th points mentioned as you did not test any of them in the end.
5. **You did not do the full refund so this is why you did not reproduce the error with the tax**, test again.
6. No, On the refund request page, **in your video, you see the Display Name of this user, and not his First Name Last Name**, so now you have tested and successfully reproduced the error, you can proceed with fixing that.

So all errors still occur. Check the video I sent in Dokan Support Ticket #21455, follow the exact same steps, from payments getaway, products ordered, up to languages and you will reproduce all the bugs mentioned in this github as even with Dokan 3.10.3, I still got the exact same errors.

Waiting for your news.

**Comment by Sophie-2e** [comment] 2024-04-26 08:38
Hello @mralaminahamed, you're welcome and glad we are all on the same page 😉

CC: @mrabbani, @tanjiralmamun

**Comment by mralaminahamed** [comment] 2024-04-26 08:40
Thank you, @Sophie-2e, for your valuable feedback and guidance throughout this process. Your detailed comments and instructions helped me thoroughly investigate and reproduce the reported issues accurately.

I have successfully addressed the actual issue. I would like to inform you that in the refund request popup, the **RMA** module was displaying the subtotal price instead of the total price. The issue occurred because the order included a coupon, which deducted the order price, but the subtotal price remained unchanged. As a result, the total price calculated after applying the coupon was different from the subtotal price being shown.

The fix for this issue will be included in our next software release, which is scheduled for the future. However, if you require the fix sooner and cannot wait for the public release, please contact our support team, and they will assist you in obtaining the patch or update before it becomes publicly available.

**Comment by Sophie-2e** [comment] 2024-04-26 08:49
@mralaminahamed Super good news! 

What about:
- the "Problem to fully refund an order because no way of adding shipping cost" via RMA requess (both refund and store credit) ?
- the user name/ display name of the customer being displayed in RMA request in Seller Dashboard when it should be first name and last name like it is in the other detail?

**Comment by mralaminahamed** [comment] 2024-04-26 10:22
> 2. The user name/display name of the customer being displayed in the RMA request in the Seller Dashboard instead of the first name and last name:

I noticed that in the screenshot you provided, you were using a user account that did not have the first name set as the display name. Instead, the username was set as the display name.

However, when I used the '**Plugin Support**' user account and checked the display name, I confirmed that the functionality is working correctly. As you can see from the attached screenshots, when the user has set their first name and last name, the RMA request section displays the customer's full name as expected.

Screenshots:
1. Client name at Refund page: [See the screenshot](https://drive.google.com/open?id=1-hx6bep93Fs0jlBvOGUq0sHEn4N2kHX4&usp=drive_fs)
2. Client name at WP Profile Page: [See the screenshot](https://drive.google.com/file/d/1-iDvuk7t6PyM2Pz_UrBsSZuSfhZlr-ew/view?usp=sharing)
3. Your client's name at WP Profile Page: [See the screenshot](https://drive.google.com/file/d/1-jcolf61SLdksE6aplHq4Wk_9766JNON/view?usp=sharing)

**Comment by mralaminahamed** [comment] 2024-04-26 10:23
> 1. the "Problem to fully refund an order because no way of adding shipping cost" via RMA request (both refund and store credit) ?

@imtiaz-pranto Please share your update for adding shipping cost for refund an order

**Comment by imtiaz-pranto** [comment] 2024-04-26 11:20
Dear @Sophie-2e , regarding the inability to include shipping costs in refunds via RMA requests, currently, our system does not support adding shipping and shipping tax calculations during the refund process. This limitation is due to our integration with Stripe, which doesn't support automated modifications for these costs at this moment. 

We will continue to explore potential solutions. In the meantime, for refunds that require shipping cost adjustments, a custom solution might be necessary. 

On a positive note, other issues related to Stripe refunds have been addressed and will be included in the next release.

This issue will be closed with this update. Thank you for your assistance.

**Comment by Sophie-2e** [comment] 2024-04-29 07:37
Happy Monday @mralaminahamed and @imtiaz-pranto,

First of all, good job @mralaminahamed! Thank you for your investigation, tests, explanations, solutions and report of the bug 👌 

Then noted for the shipping costs @imtiaz-pranto, I created a feature request on GitHub as a future improvement for later: https://github.com/getdokan/dokan/issues/2261 😉

**Closed** 2024-05-07 05:53 UTC
Labels: Has Pull Request, focus: payments
