### ISSUE TITLE
Refund Function Error with Dokan Activation

### ISSUE THREAD

**Issue by mr-gausulazam** [getdokan/dokan#2149] opened 2024-01-18 08:21 UTC
### Bug Description

When the Dokan plugin is activated, the refund function encounters a critical issue. Attempting to process a refund with fractional numbers triggers an error, preventing the proper completion of the refund process. Specifically, after adding tax and shipping charges, an error message is displayed, indicating that the maximum limit has been exceeded.

I have tried to reproduce this issue on the only WooCommerce-based marketplace. However, this issue does not reproduce to the only WooCommerce-based marketplace. 

### Step To Reproduce

- Activate the Dokan plugin on the WooCommerce-based marketplace.
- Configure tax and shipping charges with fractional numbers.
- Attempt to initiate a refund from the WooCommerce end for a Dokan vendor.

### Expected Behaviour

The refund process should execute seamlessly, allowing the vendor to receive the refund without encountering any errors related to maximum limits being crossed.

### Actual Behaviour

It display an error message like Maximum limit cross

### Additional Information

Screen recording: https://www.loom.com/share/8b05ccd5e7f44e42beb1af632f711c52

### Environment (please complete the following information)

```shell
1. Dokan Version: 3.9.6
2. Dokan Pro Version: 3.9.8
3. WooCommerce Version: 8.5.1
5. Current Theme: Store Front
```

**Comment by Mohaiminulislam1989** [comment] 2024-01-19 04:42
@shohag121 vai any update on it?

**Comment by shohag121** [comment] 2024-01-19 06:26
@Mohaiminulislam1989 Bhai, 

I was working on already assigned Issues in my sprint and this issue is just been assigned to me.
I'll start working on it as soon as possible.

Thank you.

**Comment by shohag121** [comment] 2024-01-22 08:11
Hello @mr-gausulazam Bhai,

After completing my investigation I got some questions in mind.

1. Did we change the WooCommerce number precision setting after processing the order?
2. Did we try to process order number 1582 without Dokan Pro?

![Image](https://github.com/getdokan/dokan/assets/5476784/6dda2b92-5e35-48bf-98a9-40abdc90fee6)

If you check the **Total available to refund** amount and **Refund Amount**  field, the **refund amount** exceeds the **Total available to refund amount** in the front end.


Let's discuss this issue in person along with @ Mohaiminulislam1989 Bhai.
I'll request you record another video demonstrating the result of creating a refund for order number 1582 without dokan activated.


Thank you.

**Comment by shohag121** [comment] 2024-01-23 07:27
@mr-gausulazam Bhai, as we have discussed in person the issue is not related to the Refund functionality and the issue needs to be re-evaluated, I'm closing this issue.

Please feel free to create a new issue with the findings of your investigation and data.

**Closed by shohag121** 2024-01-23 07:27 UTC
Labels: Type: Bug, urgent, focus: order, roadmap: q1-24
